# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grd_GUI.ui'
#
# Created: Wed Jul  2 11:20:37 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BlobFlowExplorer(object):
    def setupUi(self, BlobFlowExplorer):
        BlobFlowExplorer.setObjectName(_fromUtf8("BlobFlowExplorer"))
        BlobFlowExplorer.resize(700, 515)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BlobFlowExplorer.sizePolicy().hasHeightForWidth())
        BlobFlowExplorer.setSizePolicy(sizePolicy)
        self.mplwidget = MatplotlibWidget(BlobFlowExplorer)
        self.mplwidget.setGeometry(QtCore.QRect(280, 10, 400, 300))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.pushButton = QtGui.QPushButton(BlobFlowExplorer)
        self.pushButton.setGeometry(QtCore.QRect(590, 480, 90, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.timeDial = QtGui.QDial(BlobFlowExplorer)
        self.timeDial.setGeometry(QtCore.QRect(210, 370, 50, 64))
        self.timeDial.setObjectName(_fromUtf8("timeDial"))
        self.verticalLayoutWidget = QtGui.QWidget(BlobFlowExplorer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 320, 160, 113))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.Play = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.Play.setObjectName(_fromUtf8("Play"))
        self.verticalLayout.addWidget(self.Play)
        self.Rewind = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.Rewind.setObjectName(_fromUtf8("Rewind"))
        self.verticalLayout.addWidget(self.Rewind)
        self.Pause = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.Pause.setChecked(True)
        self.Pause.setObjectName(_fromUtf8("Pause"))
        self.verticalLayout.addWidget(self.Pause)
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayoutWidget = QtGui.QWidget(BlobFlowExplorer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 390, 401, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalScrollBar = QtGui.QScrollBar(self.horizontalLayoutWidget)
        self.horizontalScrollBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.horizontalLayout.addWidget(self.horizontalScrollBar)
        self.CurrentFrame = QtGui.QSpinBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentFrame.sizePolicy().hasHeightForWidth())
        self.CurrentFrame.setSizePolicy(sizePolicy)
        self.CurrentFrame.setObjectName(_fromUtf8("CurrentFrame"))
        self.horizontalLayout.addWidget(self.CurrentFrame)
        self.zoom = QtGui.QDial(BlobFlowExplorer)
        self.zoom.setGeometry(QtCore.QRect(330, 320, 50, 64))
        self.zoom.setMinimum(0)
        self.zoom.setMaximum(100)
        self.zoom.setObjectName(_fromUtf8("zoom"))
        self.label_2 = QtGui.QLabel(BlobFlowExplorer)
        self.label_2.setGeometry(QtCore.QRect(280, 350, 53, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.aspectRatio = QtGui.QDial(BlobFlowExplorer)
        self.aspectRatio.setGeometry(QtCore.QRect(470, 320, 50, 64))
        self.aspectRatio.setMaximum(10)
        self.aspectRatio.setSliderPosition(5)
        self.aspectRatio.setNotchesVisible(True)
        self.aspectRatio.setObjectName(_fromUtf8("aspectRatio"))

        self.retranslateUi(BlobFlowExplorer)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlowExplorer.quit_gui)
        QtCore.QObject.connect(self.timeDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.timeDial.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.CurrentFrame.setValue)
        QtCore.QObject.connect(self.CurrentFrame, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar.setValue)
        QtCore.QObject.connect(self.Play, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlowExplorer.play)
        QtCore.QObject.connect(self.Rewind, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlowExplorer.play)
        QtCore.QObject.connect(self.Pause, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlowExplorer.pause)
        QtCore.QObject.connect(self.CurrentFrame, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), BlobFlowExplorer.newplot)
        QtCore.QObject.connect(self.zoom, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), BlobFlowExplorer.zoomChanged)
        QtCore.QMetaObject.connectSlotsByName(BlobFlowExplorer)

    def retranslateUi(self, BlobFlowExplorer):
        BlobFlowExplorer.setWindowTitle(QtGui.QApplication.translate("BlobFlowExplorer", "BlobFlow Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("BlobFlowExplorer", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BlobFlowExplorer", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.Play.setText(QtGui.QApplication.translate("BlobFlowExplorer", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.Rewind.setText(QtGui.QApplication.translate("BlobFlowExplorer", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.Pause.setText(QtGui.QApplication.translate("BlobFlowExplorer", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.Pause.setShortcut(QtGui.QApplication.translate("BlobFlowExplorer", "Ctrl+R, Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BlobFlowExplorer", "Zoom", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
