# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initializer.ui'
#
# Created: Sat Jun 14 23:06:44 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BlobFlow_creator(object):
    def setupUi(self, BlobFlow_creator):
        BlobFlow_creator.setObjectName(_fromUtf8("BlobFlow_creator"))
        BlobFlow_creator.resize(900, 578)
        self.plotButton = QtGui.QPushButton(BlobFlow_creator)
        self.plotButton.setGeometry(QtCore.QRect(420, 180, 90, 24))
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.label = QtGui.QLabel(BlobFlow_creator)
        self.label.setGeometry(QtCore.QRect(410, 10, 53, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayoutWidget = QtGui.QWidget(BlobFlow_creator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(410, 70, 111, 90))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.yDomainMax = QtGui.QLineEdit(self.gridLayoutWidget)
        self.yDomainMax.setObjectName(_fromUtf8("yDomainMax"))
        self.gridLayout.addWidget(self.yDomainMax, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.xDomainMax = QtGui.QLineEdit(self.gridLayoutWidget)
        self.xDomainMax.setObjectName(_fromUtf8("xDomainMax"))
        self.gridLayout.addWidget(self.xDomainMax, 0, 1, 1, 1)
        self.yDomainMin = QtGui.QLineEdit(self.gridLayoutWidget)
        self.yDomainMin.setObjectName(_fromUtf8("yDomainMin"))
        self.gridLayout.addWidget(self.yDomainMin, 2, 0, 1, 1)
        self.xDomainMin = QtGui.QLineEdit(self.gridLayoutWidget)
        self.xDomainMin.setObjectName(_fromUtf8("xDomainMin"))
        self.gridLayout.addWidget(self.xDomainMin, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(BlobFlow_creator)
        self.label_7.setGeometry(QtCore.QRect(140, 10, 181, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.saveButton = QtGui.QPushButton(BlobFlow_creator)
        self.saveButton.setGeometry(QtCore.QRect(10, 520, 141, 24))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.saveFun = QtGui.QPushButton(BlobFlow_creator)
        self.saveFun.setGeometry(QtCore.QRect(10, 260, 101, 24))
        self.saveFun.setObjectName(_fromUtf8("saveFun"))
        self.pushButton = QtGui.QPushButton(BlobFlow_creator)
        self.pushButton.setGeometry(QtCore.QRect(310, 520, 90, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.loadFun = QtGui.QPushButton(BlobFlow_creator)
        self.loadFun.setGeometry(QtCore.QRect(300, 260, 101, 24))
        self.loadFun.setObjectName(_fromUtf8("loadFun"))
        self.verticalLayoutWidget = QtGui.QWidget(BlobFlow_creator)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 391, 221))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.verticalLayoutWidget_2 = QtGui.QWidget(BlobFlow_creator)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 30, 311, 521))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mplwidget = MatplotlibWidget(self.verticalLayoutWidget_2)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.verticalLayout_2.addWidget(self.mplwidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.nMesh = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.nMesh.setObjectName(_fromUtf8("nMesh"))
        self.horizontalLayout.addWidget(self.nMesh)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.interpPopControl = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.interpPopControl.setObjectName(_fromUtf8("interpPopControl"))
        self.horizontalLayout_2.addWidget(self.interpPopControl)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.FieldInterpolateButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.FieldInterpolateButton.setObjectName(_fromUtf8("FieldInterpolateButton"))
        self.verticalLayout_2.addWidget(self.FieldInterpolateButton)
        self.projectPreview = MatplotlibWidget(self.verticalLayoutWidget_2)
        self.projectPreview.setObjectName(_fromUtf8("projectPreview"))
        self.verticalLayout_2.addWidget(self.projectPreview)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(4, 5)
        self.Log = QtGui.QPlainTextEdit(BlobFlow_creator)
        self.Log.setGeometry(QtCore.QRect(10, 320, 391, 181))
        self.Log.setReadOnly(False)
        self.Log.setObjectName(_fromUtf8("Log"))
        self.label_6 = QtGui.QLabel(BlobFlow_creator)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 54, 15))
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(BlobFlow_creator)
        QtCore.QObject.connect(self.plotButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlow_creator.plotFunction)
        QtCore.QObject.connect(self.xDomainMin, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BlobFlow_creator.xMinChanged)
        QtCore.QObject.connect(self.xDomainMax, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BlobFlow_creator.xMaxChanged)
        QtCore.QObject.connect(self.yDomainMin, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BlobFlow_creator.yMinChanged)
        QtCore.QObject.connect(self.yDomainMax, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BlobFlow_creator.yMaxChanged)
        QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlow_creator.saveDataFile)
        QtCore.QObject.connect(self.saveFun, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlow_creator.saveFunction)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlow_creator.quitGUI)
        QtCore.QObject.connect(self.loadFun, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlow_creator.loadFunction)
        QtCore.QObject.connect(self.nMesh, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BlobFlow_creator.nMeshChanged)
        QtCore.QObject.connect(self.FieldInterpolateButton, QtCore.SIGNAL(_fromUtf8("clicked()")), BlobFlow_creator.plotProject)
        QtCore.QObject.connect(self.interpPopControl, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), BlobFlow_creator.interpPopControlChanged)
        QtCore.QObject.connect(self.nMesh, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BlobFlow_creator.plotProject)
        QtCore.QObject.connect(self.interpPopControl, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BlobFlow_creator.plotProject)
        QtCore.QObject.connect(self.xDomainMin, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BlobFlow_creator.plotFunction)
        QtCore.QObject.connect(self.yDomainMin, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BlobFlow_creator.plotFunction)
        QtCore.QObject.connect(self.xDomainMax, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BlobFlow_creator.plotFunction)
        QtCore.QObject.connect(self.yDomainMax, QtCore.SIGNAL(_fromUtf8("returnPressed()")), BlobFlow_creator.plotFunction)
        QtCore.QMetaObject.connectSlotsByName(BlobFlow_creator)

    def retranslateUi(self, BlobFlow_creator):
        BlobFlow_creator.setWindowTitle(QtGui.QApplication.translate("BlobFlow_creator", "BlobFlow Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setText(QtGui.QApplication.translate("BlobFlow_creator", "> Plot >", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BlobFlow_creator", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.yDomainMax.setText(QtGui.QApplication.translate("BlobFlow_creator", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BlobFlow_creator", "xMax", None, QtGui.QApplication.UnicodeUTF8))
        self.xDomainMax.setText(QtGui.QApplication.translate("BlobFlow_creator", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.yDomainMin.setText(QtGui.QApplication.translate("BlobFlow_creator", "-1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.xDomainMin.setText(QtGui.QApplication.translate("BlobFlow_creator", "-1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BlobFlow_creator", "xMin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BlobFlow_creator", "yMin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BlobFlow_creator", "yMax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BlobFlow_creator", "Initial condition entry", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("BlobFlow_creator", "Create sim data file", None, QtGui.QApplication.UnicodeUTF8))
        self.saveFun.setText(QtGui.QApplication.translate("BlobFlow_creator", "Save function", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("BlobFlow_creator", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFun.setText(QtGui.QApplication.translate("BlobFlow_creator", "Load function", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_2.setPlainText(QtGui.QApplication.translate("BlobFlow_creator", "def f(x,y):\n"
"    w=numpy.empty_like (x)", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("BlobFlow_creator", "    w   = cos(x)*sin(y)\n"
"    ind = (x>2) & (x<6) & (y>5) & (y<8)\n"
"    w[ind] = exp(-(x[ind]**2+y[ind]**2)/50)\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_3.setPlainText(QtGui.QApplication.translate("BlobFlow_creator", "return(w)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BlobFlow_creator", "Mesh points: ", None, QtGui.QApplication.UnicodeUTF8))
        self.nMesh.setText(QtGui.QApplication.translate("BlobFlow_creator", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BlobFlow_creator", "Interp. Pop. Control: ", None, QtGui.QApplication.UnicodeUTF8))
        self.interpPopControl.setText(QtGui.QApplication.translate("BlobFlow_creator", "1.0e-4", None, QtGui.QApplication.UnicodeUTF8))
        self.FieldInterpolateButton.setText(QtGui.QApplication.translate("BlobFlow_creator", "\\/ Field interpolate \\/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BlobFlow_creator", "Log", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
