# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mpltest.ui'
#
# Created: Fri Oct  4 14:47:31 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(700, 515)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.mplwidget = MatplotlibWidget(Form)
        self.mplwidget.setGeometry(QtCore.QRect(280, 10, 400, 300))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(590, 480, 90, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.timeDial = QtGui.QDial(Form)
        self.timeDial.setGeometry(QtCore.QRect(210, 370, 50, 64))
        self.timeDial.setObjectName(_fromUtf8("timeDial"))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 320, 160, 113))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.Play = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.Play.setObjectName(_fromUtf8("Play"))
        self.verticalLayout.addWidget(self.Play)
        self.Rewind = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.Rewind.setObjectName(_fromUtf8("Rewind"))
        self.verticalLayout.addWidget(self.Rewind)
        self.Pause = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.Pause.setChecked(True)
        self.Pause.setObjectName(_fromUtf8("Pause"))
        self.verticalLayout.addWidget(self.Pause)
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 390, 401, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalScrollBar = QtGui.QScrollBar(self.horizontalLayoutWidget)
        self.horizontalScrollBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.horizontalLayout.addWidget(self.horizontalScrollBar)
        self.CurrentFrame = QtGui.QSpinBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentFrame.sizePolicy().hasHeightForWidth())
        self.CurrentFrame.setSizePolicy(sizePolicy)
        self.CurrentFrame.setObjectName(_fromUtf8("CurrentFrame"))
        self.horizontalLayout.addWidget(self.CurrentFrame)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(280, 320, 401, 52))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.xMin = QtGui.QDoubleSpinBox(self.widget)
        self.xMin.setMinimum(-1000.0)
        self.xMin.setMaximum(1000.0)
        self.xMin.setObjectName(_fromUtf8("xMin"))
        self.horizontalLayout_2.addWidget(self.xMin)
        self.xMinDial = QtGui.QDial(self.widget)
        self.xMinDial.setObjectName(_fromUtf8("xMinDial"))
        self.horizontalLayout_2.addWidget(self.xMinDial)
        self.xMaxDial = QtGui.QDial(self.widget)
        self.xMaxDial.setObjectName(_fromUtf8("xMaxDial"))
        self.horizontalLayout_2.addWidget(self.xMaxDial)
        self.xMax = QtGui.QDoubleSpinBox(self.widget)
        self.xMax.setMinimum(-1000.0)
        self.xMax.setMaximum(1000.0)
        self.xMax.setProperty("value", 1.0)
        self.xMax.setObjectName(_fromUtf8("xMax"))
        self.horizontalLayout_2.addWidget(self.xMax)
        self.widget1 = QtGui.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(209, 10, 61, 301))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.yMax = QtGui.QDoubleSpinBox(self.widget1)
        self.yMax.setMinimum(-1000.0)
        self.yMax.setMaximum(1000.0)
        self.yMax.setSingleStep(0.1)
        self.yMax.setProperty("value", 1.0)
        self.yMax.setObjectName(_fromUtf8("yMax"))
        self.verticalLayout_2.addWidget(self.yMax)
        self.yMaxDial = QtGui.QDial(self.widget1)
        self.yMaxDial.setObjectName(_fromUtf8("yMaxDial"))
        self.verticalLayout_2.addWidget(self.yMaxDial)
        self.yMinDial = QtGui.QDial(self.widget1)
        self.yMinDial.setObjectName(_fromUtf8("yMinDial"))
        self.verticalLayout_2.addWidget(self.yMinDial)
        self.yMin = QtGui.QDoubleSpinBox(self.widget1)
        self.yMin.setMinimum(-1000.0)
        self.yMin.setMaximum(1000.0)
        self.yMin.setObjectName(_fromUtf8("yMin"))
        self.verticalLayout_2.addWidget(self.yMin)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.quit_gui)
        QtCore.QObject.connect(self.timeDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.timeDial.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.CurrentFrame.setValue)
        QtCore.QObject.connect(self.CurrentFrame, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar.setValue)
        QtCore.QObject.connect(self.Play, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.play)
        QtCore.QObject.connect(self.Rewind, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.play)
        QtCore.QObject.connect(self.Pause, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.pause)
        QtCore.QObject.connect(self.xMin, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.newplot)
        QtCore.QObject.connect(self.xMax, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.newplot)
        QtCore.QObject.connect(self.yMin, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.newplot)
        QtCore.QObject.connect(self.yMax, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.newplot)
        QtCore.QObject.connect(self.CurrentFrame, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.newplot)
        QtCore.QObject.connect(self.yMinDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.yMinDialChanged)
        QtCore.QObject.connect(self.yMaxDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.yMaxDialChanged)
        QtCore.QObject.connect(self.xMinDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.xMinDialChanged)
        QtCore.QObject.connect(self.xMaxDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.xMaxDialChanged)
        QtCore.QObject.connect(self.yMin, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.yMinChanged)
        QtCore.QObject.connect(self.xMin, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Form.xMinChanged)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.Play.setText(QtGui.QApplication.translate("Form", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.Rewind.setText(QtGui.QApplication.translate("Form", "Rewind", None, QtGui.QApplication.UnicodeUTF8))
        self.Pause.setText(QtGui.QApplication.translate("Form", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.Pause.setShortcut(QtGui.QApplication.translate("Form", "Ctrl+R, Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
